<?php 
/********************************************************************************* 
 *  This file is part of HRMS-Cprog.
 *  Copyright (C) 2015 Carlos Pinto
 *   
 *  HRMS-Cprog is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  HRMS-Cprog is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  HRMS-Cprog Support <kkobtk@gmail.com>
 ********************************************************************************/  
?>

<?php 
$options_data = "";	
$options_data .= sapp_Global::selectOptionBuilder('', 'Select An Employee');
if($this->flag == 'true')
{
    if(count($this->employee_data) >0)
    {
        foreach ($this->employee_data as $data) 
        {                
            $options_data .= sapp_Global::selectOptionBuilder($data['user_id'],ucwords(utf8_encode($data['userfullname'])),$data['profileimg'],$data['jobtitle_id'],$data['jobtitle_name'],$data['employeeId'],$data['reporting_manager'],$data['reporting_manager_name']);
        }
    }        
    echo $options_data;
}
else
{
    echo "noemployees.";
}

?> 
 